/* SPDX-License-Identifier: Apache-2.0 */
/** Reviewed Salesforce B2C Commerce MCP tool contract. */
import { defineTools } from "./tool-contract-types.ts";

export const B2C_COMMERCE_TOOLS = defineTools([
  [
    "skills_read",
    "Discover and read packaged B2C Commerce development and operations guidance.",
    "Guidance",
    "read",
  ],
  [
    "docs_search",
    "Search B2C Commerce developer, merchant, Script API, job-step, and tooling documentation.",
    "Documentation",
    "read",
  ],
  [
    "docs_read",
    "Read one B2C Commerce documentation entry by identifier or fuzzy query.",
    "Documentation",
    "read",
  ],
  ["docs_list", "List B2C Commerce documentation identifiers and titles.", "Documentation", "read"],
  [
    "docs_schema_search",
    "Search bundled B2C Commerce XSD schemas.",
    "Schema documentation",
    "read",
  ],
  ["docs_schema_read", "Read one bundled B2C Commerce XSD schema.", "Schema documentation", "read"],
  [
    "docs_schema_list",
    "List bundled B2C Commerce XSD schema identifiers.",
    "Schema documentation",
    "read",
  ],
  [
    "config_inspect",
    "Inspect resolved B2C Commerce configuration, sources, paths, and warnings.",
    "Configuration",
    "read",
  ],
  [
    "cartridge_deploy",
    "Deploy cartridges or selected files through WebDAV and optionally reload the code version.",
    "Cartridge deployment",
    "destructive",
  ],
  [
    "webdav_list",
    "List one B2C Commerce WebDAV directory with bounded metadata.",
    "WebDAV",
    "read",
  ],
  [
    "webdav_get",
    "Read ranged WebDAV text or download one bounded file to the MCP host.",
    "WebDAV",
    "read",
  ],
  ["webdav_put", "Upload or replace one WebDAV file.", "WebDAV", "destructive"],
  [
    "logs_list_files",
    "List instance log files and prefixes available for inspection.",
    "Instance diagnostics",
    "read",
  ],
  [
    "logs_get_recent",
    "Fetch recent bounded B2C Commerce instance logs.",
    "Instance diagnostics",
    "read",
  ],
  [
    "logs_watch",
    "Start, list, or stop a bounded instance-log watch.",
    "Instance diagnostics",
    "read",
  ],
  [
    "logs_watch_poll",
    "Read buffered events from an instance-log watch.",
    "Instance diagnostics",
    "read",
  ],
  [
    "mrt_logs_watch",
    "Start, list, or stop a Managed Runtime log watch.",
    "Managed Runtime diagnostics",
    "read",
  ],
  [
    "mrt_logs_watch_poll",
    "Read buffered events from a Managed Runtime log watch.",
    "Managed Runtime diagnostics",
    "read",
  ],
  [
    "debug_list_sessions",
    "List debugger sessions, breakpoints, and halted threads.",
    "Script debugging",
    "read",
  ],
  [
    "debug_start_session",
    "Start a script debugger session and map local cartridges.",
    "Script debugging",
    "write",
  ],
  [
    "debug_end_session",
    "Disconnect and release a script debugger session.",
    "Script debugging",
    "write",
  ],
  [
    "debug_set_breakpoints",
    "Replace the breakpoints associated with a debugger session.",
    "Script debugging",
    "write",
  ],
  ["debug_wait_for_stop", "Wait for a debugger thread to halt.", "Script debugging", "read"],
  [
    "debug_inspect",
    "Inspect stack frames and variables on a halted thread.",
    "Script debugging",
    "read",
  ],
  [
    "debug_evaluate",
    "Evaluate JavaScript in a halted debugger frame; evaluation can change remote state.",
    "Script debugging",
    "write",
  ],
  ["debug_control", "Resume or step a halted debugger thread.", "Script debugging", "write"],
  [
    "debug_capture_at_breakpoint",
    "Add a breakpoint, wait for a halt, and capture debugger state.",
    "Script debugging",
    "write",
  ],
  [
    "mrt_bundle_push",
    "Push a pre-built storefront bundle to Managed Runtime and optionally deploy it.",
    "Managed Runtime deployment",
    "write",
  ],
  [
    "scapi_search",
    "Search bundled or live SCAPI contracts for operations, inputs, and required scopes.",
    "SCAPI discovery",
    "read",
  ],
  [
    "scapi_execute",
    "Execute arbitrary governed SCAPI Admin or Shopper operations through code mode.",
    "SCAPI execution",
    "destructive",
  ],
  [
    "scapi_snippet_save",
    "Save a completed SCAPI execution as a reusable local workflow snippet.",
    "SCAPI workflows",
    "write",
  ],
  [
    "scapi_custom_apis_get_status",
    "Read Custom SCAPI endpoint registration status by site.",
    "SCAPI administration",
    "read",
  ],
  [
    "scapi_schemas_list",
    "List SCAPI schema metadata or fetch one OpenAPI contract.",
    "SCAPI discovery",
    "read",
  ],
  [
    "metrics_get",
    "Read bounded B2C Commerce observability metric time series when available.",
    "Observability",
    "read",
  ],
  [
    "cip_discover",
    "Discover Commerce Intelligence Platform reports, tables, parameters, and columns.",
    "Commerce analytics",
    "read",
  ],
  [
    "cip_query",
    "Run a bounded Commerce Intelligence Platform report or analytical SQL query.",
    "Commerce analytics",
    "read",
  ],
] as const);
