/* SPDX-License-Identifier: Apache-2.0 */
/** MuleSoft DX MCP tools documented in the official command summary. */
import { defineTools } from "./tool-contract-types.ts";

export const MULESOFT_DX_TOOLS = defineTools([
  [
    "configure_agent_network_yaml",
    "Configure or edit an agent network project YAML file.",
    "Agent network development",
    "write",
  ],
  [
    "create_agent_network_project",
    "Create and scaffold an agent network project.",
    "Agent network development",
    "write",
  ],
  [
    "deploy_agent_network",
    "Deploy an agent network project.",
    "Agent network development",
    "write",
  ],
  [
    "publish_agent_network_assets",
    "Publish agent network assets.",
    "Agent network development",
    "write",
  ],
  [
    "create_and_manage_assets",
    "Create, update, or delete assets in Anypoint Exchange.",
    "Exchange asset management",
    "mixed",
  ],
  [
    "create_and_manage_metadata",
    "Define, attach, or update Mule flow metadata.",
    "Application development",
    "write",
  ],
  ["create_api_spec_project", "Create an API specification project.", "API design", "write"],
  ["create_MCP_server", "Create an MCP server project.", "Application development", "write"],
  ["create_mule_project", "Create a Mule application project.", "Application development", "write"],
  [
    "generate_api_spec",
    "Generate an API specification from natural-language requirements.",
    "API design",
    "write",
  ],
  [
    "generate_mule_flow",
    "Generate a Mule flow from natural-language requirements.",
    "Application development",
    "write",
  ],
  [
    "generate_or_modify_munit_test",
    "Generate or modify an MUnit test.",
    "Application testing",
    "write",
  ],
  [
    "get_topics_agent_actions_metadata_instructions",
    "Get instructions for agent topic, action, and metadata work.",
    "Agent development guidance",
    "read",
  ],
  [
    "implement_api_spec",
    "Implement an API specification in a Mule application.",
    "API implementation",
    "write",
  ],
  ["mock_api_spec", "Create or run a mock for an API specification.", "API design", "write"],
  ["open_project", "Open a MuleSoft project in the supported IDE.", "Project navigation", "write"],
  [
    "run_local_mule_application",
    "Run a Mule application locally.",
    "Application execution",
    "mixed",
  ],
  ["search_asset", "Search for assets in Anypoint Exchange.", "Exchange asset discovery", "read"],
  ["test_connection", "Test a Mule application connection.", "Connection testing", "read"],
  ["validate_project", "Validate a MuleSoft project.", "Project validation", "read"],
  [
    "uc_add_pagination",
    "Add pagination support to a generated connector.",
    "Connector development",
    "write",
  ],
  [
    "uc_connector_lifecycle",
    "Manage connector development lifecycle tasks.",
    "Connector development",
    "mixed",
  ],
  [
    "uc_create_connector_workflow",
    "Create a connector development workflow.",
    "Connector development",
    "write",
  ],
  [
    "uc_generate_connector",
    "Generate a connector implementation.",
    "Connector development",
    "write",
  ],
  ["uc_generate_tests", "Generate connector tests.", "Connector testing", "write"],
  [
    "uc_get_test_generation_info",
    "Get connector test-generation information.",
    "Connector testing",
    "read",
  ],
  [
    "uc_list_connection_profiles",
    "List connector connection profiles.",
    "Connector discovery",
    "read",
  ],
  [
    "uc_manage_api_spec",
    "Create or update the API specification used by a connector.",
    "Connector development",
    "write",
  ],
  [
    "uc_manage_operations",
    "Create or update connector operations.",
    "Connector development",
    "write",
  ],
  [
    "dataweave_create_documentation",
    "Create documentation for DataWeave code.",
    "DataWeave development",
    "write",
  ],
  ["dataweave_create_project", "Create a DataWeave project.", "DataWeave development", "write"],
  [
    "dataweave_create_sample_data",
    "Create sample data for DataWeave development.",
    "DataWeave development",
    "write",
  ],
  [
    "dataweave_get_module_metadata",
    "Get metadata for a DataWeave module.",
    "DataWeave inspection",
    "read",
  ],
  [
    "dataweave_get_project_metadata",
    "Get metadata for a DataWeave project.",
    "DataWeave inspection",
    "read",
  ],
  ["dataweave_open_project", "Open a DataWeave project.", "Project navigation", "write"],
  ["dataweave_run_script_tool", "Run a DataWeave script.", "DataWeave execution", "mixed"],
  [
    "create_and_manage_api_instances",
    "Create or configure API Manager instances.",
    "API management",
    "write",
  ],
  [
    "deploy_mule_application",
    "Deploy a Mule application to Anypoint Runtime Manager.",
    "Application deployment",
    "write",
  ],
  ["list_api_instances", "List API Manager instances.", "API management discovery", "read"],
  [
    "list_applications",
    "List applications and optionally retrieve metrics or logs.",
    "Application monitoring",
    "read",
  ],
  [
    "update_mule_application",
    "Update a deployed Mule application.",
    "Application deployment",
    "write",
  ],
  [
    "add_governance_ruleset",
    "Add an API governance ruleset to a project.",
    "API governance",
    "write",
  ],
  [
    "list_governance_rulesets",
    "List governance rulesets and their rules.",
    "API governance",
    "read",
  ],
  [
    "validate_api_against_ruleset",
    "Validate an API against a governance ruleset.",
    "API governance",
    "read",
  ],
  [
    "get_flex_gateway_policy_example",
    "Get an example Flex Gateway policy.",
    "Policy guidance",
    "read",
  ],
  [
    "manage_api_instance_policy",
    "Apply or update a policy on an API instance.",
    "Policy management",
    "write",
  ],
  [
    "manage_flex_gateway_policy_project",
    "Get guidance for managing an Omni Gateway custom policy project.",
    "Policy development",
    "read",
  ],
  [
    "get_platform_insights",
    "Get Anypoint Platform operational insights.",
    "Usage and insights",
    "read",
  ],
  ["get_reuse_metrics", "Get Anypoint asset reuse metrics.", "Usage and insights", "read"],
]);
