/* SPDX-License-Identifier: Apache-2.0 */
/** Marketing Cloud Engagement MCP tools from the official category references. */
import { defineTools } from "./tool-contract-types.ts";

export const MARKETING_CLOUD_TOOLS = defineTools([
  ["sfmc_create_automation", "Create an Automation Studio automation.", "Automations", "write"],
  [
    "sfmc_create_automation_file_transfer",
    "Create an Automation Studio file transfer activity.",
    "Automations",
    "write",
  ],
  ["sfmc_create_ftp_location", "Create a file transfer location.", "Automations", "write"],
  ["sfmc_create_sql_query", "Create a SQL query activity.", "Automations", "write"],
  [
    "sfmc_delete_automation_file_transfer",
    "Delete an Automation Studio file transfer activity.",
    "Automations",
    "destructive",
  ],
  [
    "sfmc_delete_ftp_location",
    "Deactivate a file transfer location.",
    "Automations",
    "destructive",
  ],
  ["sfmc_execute_script_activity", "Execute an SSJS activity.", "Automations", "write"],
  ["sfmc_get_automation", "Retrieve an automation.", "Automations", "read"],
  ["sfmc_get_automation_categories", "List automation folders.", "Automations", "read"],
  [
    "sfmc_get_automation_file_transfer",
    "Retrieve one Automation Studio file transfer activity.",
    "Automations",
    "read",
  ],
  [
    "sfmc_get_automation_file_transfers",
    "List Automation Studio file transfer activities.",
    "Automations",
    "read",
  ],
  [
    "sfmc_get_automation_filters",
    "List Automation Studio filter activities.",
    "Automations",
    "read",
  ],
  [
    "sfmc_get_automation_filter_definitions",
    "List filter definitions used by automation filters.",
    "Automations",
    "read",
  ],
  [
    "sfmc_get_automation_ftp_locations",
    "List Automation Studio file transfer locations.",
    "Automations",
    "read",
  ],
  [
    "sfmc_get_automation_imports",
    "List Automation Studio import file activities.",
    "Automations",
    "read",
  ],
  [
    "sfmc_get_automation_instance",
    "Retrieve one automation execution instance.",
    "Automations",
    "read",
  ],
  ["sfmc_get_automation_scripts", "List Automation Studio SSJS activities.", "Automations", "read"],
  [
    "sfmc_get_automation_trigger_status",
    "Check an automation trigger API request.",
    "Automations",
    "read",
  ],
  ["sfmc_get_automations", "List automations.", "Automations", "read"],
  ["sfmc_get_ftp_location", "Retrieve a file transfer location.", "Automations", "read"],
  ["sfmc_get_sql_queries", "List SQL query activities.", "Automations", "read"],
  ["sfmc_get_sql_query", "Retrieve a SQL query activity.", "Automations", "read"],
  ["sfmc_run_automation", "Run an automation immediately.", "Automations", "write"],
  [
    "sfmc_run_automation_activities",
    "Run selected automation activities by ID.",
    "Automations",
    "write",
  ],
  [
    "sfmc_run_automation_activities_by_key",
    "Run selected automation activities by external key.",
    "Automations",
    "write",
  ],
  ["sfmc_run_sql_query", "Execute a SQL query activity.", "Automations", "write"],
  [
    "sfmc_start_automation_file_transfer",
    "Run a file transfer activity immediately.",
    "Automations",
    "write",
  ],
  ["sfmc_update_automation", "Update an automation.", "Automations", "destructive"],
  [
    "sfmc_update_automation_file_transfer",
    "Update a file transfer activity.",
    "Automations",
    "destructive",
  ],
  [
    "sfmc_update_automation_file_trigger",
    "Activate or deactivate an automation file trigger by ID.",
    "Automations",
    "destructive",
  ],
  [
    "sfmc_update_automation_file_trigger_by_key",
    "Activate or deactivate an automation file trigger by key.",
    "Automations",
    "destructive",
  ],
  [
    "sfmc_update_automation_trigger",
    "Activate or deactivate an automation schedule trigger.",
    "Automations",
    "destructive",
  ],
  ["sfmc_update_ftp_location", "Update a file transfer location.", "Automations", "destructive"],
  ["sfmc_update_sql_query", "Update a SQL query activity.", "Automations", "destructive"],
  ["sfmc_validate_sql_query", "Validate SQL query text.", "Automations", "read"],

  ["sfmc_associate_campaign_asset", "Associate an asset with a campaign.", "Campaigns", "write"],
  ["sfmc_create_campaign", "Create a campaign.", "Campaigns", "write"],
  ["sfmc_delete_campaign", "Delete a campaign.", "Campaigns", "destructive"],
  ["sfmc_get_campaign", "Retrieve campaign details.", "Campaigns", "read"],
  ["sfmc_get_campaign_assets", "List assets associated with a campaign.", "Campaigns", "read"],
  ["sfmc_get_campaigns", "List campaigns.", "Campaigns", "read"],
  ["sfmc_remove_campaign_asset", "Remove an asset from a campaign.", "Campaigns", "destructive"],
  ["sfmc_update_campaign", "Update a campaign.", "Campaigns", "destructive"],

  ["sfmc_delete_contacts", "Delete contacts and their attributes.", "Contacts", "destructive"],
  [
    "sfmc_get_attribute_set_by_name",
    "Retrieve data from an attribute set by name.",
    "Contacts",
    "read",
  ],
  [
    "sfmc_get_attribute_set_definition",
    "Retrieve an attribute set definition.",
    "Contacts",
    "read",
  ],
  [
    "sfmc_get_attribute_set_definitions",
    "List contact-model attribute set definitions.",
    "Contacts",
    "read",
  ],
  [
    "sfmc_get_contact_key_by_email_address",
    "Retrieve contact keys by email address.",
    "Contacts",
    "read",
  ],
  ["sfmc_get_email_subscription_status", "Retrieve a subscriber email status.", "Contacts", "read"],
  ["sfmc_get_list_subscribers", "Retrieve members of a classic list.", "Contacts", "read"],
  [
    "sfmc_get_push_opt_in_status_by_subscriber_key",
    "Retrieve a subscriber push status.",
    "Contacts",
    "read",
  ],
  ["sfmc_retrieve_contact_status", "Retrieve a contact status.", "Contacts", "read"],
  ["sfmc_search_attributes", "Search available attribute sets.", "Contacts", "read"],
  [
    "sfmc_update_contact_attributes",
    "Update contact attributes in a profile or data extension.",
    "Contacts",
    "destructive",
  ],

  ["sfmc_create_content_builder_asset", "Create a Content Builder asset.", "Content", "write"],
  ["sfmc_create_content_folder", "Create a Content Builder folder.", "Content", "write"],
  ["sfmc_create_email", "Create an HTML email asset.", "Content", "write"],
  ["sfmc_create_email_template", "Create an email template asset.", "Content", "write"],
  ["sfmc_create_sms", "Create an SMS message asset.", "Content", "write"],
  ["sfmc_delete_content_folder", "Delete a Content Builder folder.", "Content", "destructive"],
  [
    "sfmc_get_content_assets",
    "Query Content Builder assets with simple filters.",
    "Content",
    "read",
  ],
  ["sfmc_get_content_builder_asset", "Retrieve a Content Builder asset by ID.", "Content", "read"],
  ["sfmc_get_content_builder_asset_types", "List Content Builder asset types.", "Content", "read"],
  ["sfmc_get_content_categories", "List Content Builder folders.", "Content", "read"],
  [
    "sfmc_search_content_builder_assets",
    "Search Content Builder assets with advanced queries.",
    "Content",
    "read",
  ],
  [
    "sfmc_update_content_builder_asset",
    "Update a Content Builder asset.",
    "Content",
    "destructive",
  ],
  [
    "sfmc_update_content_folder",
    "Rename or move a Content Builder folder.",
    "Content",
    "destructive",
  ],

  [
    "sfmc_bulk_upsert_data_extension_rows",
    "Asynchronously bulk upsert data extension rows.",
    "Data extensions",
    "write",
  ],
  [
    "sfmc_bulk_upsert_data_event_rows",
    "Batch upsert data extension rows by external key.",
    "Data extensions",
    "write",
  ],
  [
    "sfmc_clear_data_extension_data",
    "Clear all data from a data extension.",
    "Data extensions",
    "destructive",
  ],
  ["sfmc_create_data_extension", "Create a data extension.", "Data extensions", "write"],
  [
    "sfmc_create_data_extension_field_async",
    "Asynchronously add fields to a data extension.",
    "Data extensions",
    "write",
  ],
  ["sfmc_delete_data_extension", "Delete a data extension.", "Data extensions", "destructive"],
  [
    "sfmc_get_bulk_job_status",
    "Get an asynchronous bulk-data job status.",
    "Data extensions",
    "read",
  ],
  ["sfmc_get_bulk_job_results", "Get completed bulk-data job results.", "Data extensions", "read"],
  ["sfmc_get_data_extension", "Retrieve a data extension.", "Data extensions", "read"],
  [
    "sfmc_get_data_extension_fields",
    "Retrieve data extension field definitions.",
    "Data extensions",
    "read",
  ],
  ["sfmc_get_data_extension_folders", "List data extension folders.", "Data extensions", "read"],
  [
    "sfmc_get_data_extension_link",
    "Create a direct Marketing Cloud UI link to a data extension.",
    "Data extensions",
    "read",
  ],
  ["sfmc_get_data_extensions", "Search and list data extensions.", "Data extensions", "read"],
  [
    "sfmc_get_data_extensions_by_category",
    "List data extensions in a folder.",
    "Data extensions",
    "read",
  ],
  [
    "sfmc_query_data_extension_rows",
    "Query data extension rows with filtering and pagination.",
    "Data extensions",
    "read",
  ],
  [
    "sfmc_retrieve_data_extension_record",
    "Retrieve one data extension row.",
    "Data extensions",
    "read",
  ],
  [
    "sfmc_update_data_extension",
    "Update data extension properties.",
    "Data extensions",
    "destructive",
  ],
  [
    "sfmc_update_data_extension_field_async",
    "Asynchronously update data extension fields.",
    "Data extensions",
    "destructive",
  ],
  [
    "sfmc_upsert_data_extension_record",
    "Insert or update one data extension row.",
    "Data extensions",
    "write",
  ],

  [
    "sfmc_create_email_send_definition",
    "Create a transactional email send definition.",
    "Email",
    "write",
  ],
  [
    "sfmc_create_triggered_send_definition",
    "Create a triggered send definition.",
    "Email",
    "write",
  ],
  [
    "sfmc_get_transactional_send_status",
    "Get a transactional email request status.",
    "Email",
    "read",
  ],
  ["sfmc_get_triggered_send_summary", "Retrieve triggered-send metrics.", "Email", "read"],
  ["sfmc_send_transactional_email", "Send a transactional email.", "Email", "write"],

  ["sfmc_api_event_trigger", "Create an API event trigger for journey entry.", "Journeys", "write"],
  ["sfmc_create_event_definition", "Define an event that triggers a journey.", "Journeys", "write"],
  [
    "sfmc_create_journey",
    "Route a journey request to the appropriate creation tool.",
    "Journeys",
    "write",
  ],
  ["sfmc_create_journey_builder_journey", "Create a Journey Builder journey.", "Journeys", "write"],
  [
    "sfmc_data_extension_trigger",
    "Create a data extension journey-entry trigger.",
    "Journeys",
    "write",
  ],
  [
    "sfmc_decision_split_activity",
    "Construct an in-memory journey decision split activity.",
    "Journeys",
    "read",
  ],
  ["sfmc_delete_event_definition", "Delete a journey event definition.", "Journeys", "destructive"],
  ["sfmc_delete_journey", "Delete a journey.", "Journeys", "destructive"],
  [
    "sfmc_einstein_engagement_frequency_activity",
    "Construct an in-memory Einstein Engagement Frequency activity.",
    "Journeys",
    "read",
  ],
  [
    "sfmc_einstein_sto_activity",
    "Construct an in-memory Einstein Send Time Optimization activity.",
    "Journeys",
    "read",
  ],
  ["sfmc_email_activity", "Construct an in-memory journey email activity.", "Journeys", "read"],
  [
    "sfmc_engagement_decision_activity",
    "Construct an in-memory engagement decision activity.",
    "Journeys",
    "read",
  ],
  [
    "sfmc_exit_contact_from_journey",
    "Remove a contact from an active journey.",
    "Journeys",
    "write",
  ],
  [
    "sfmc_exit_contact_from_journey_status",
    "Check a journey-contact removal request.",
    "Journeys",
    "read",
  ],
  [
    "sfmc_fire_journey_event",
    "Fire an event to add a contact or signal a wait activity.",
    "Journeys",
    "write",
  ],
  ["sfmc_get_event_definition", "Retrieve a journey event definition.", "Journeys", "read"],
  ["sfmc_get_event_definitions", "List journey event definitions.", "Journeys", "read"],
  ["sfmc_get_journey", "Retrieve journey steps and configuration.", "Journeys", "read"],
  ["sfmc_get_journey_link", "Get a direct Journey Builder UI link.", "Journeys", "read"],
  ["sfmc_get_journey_publish_status", "Check a journey publication status.", "Journeys", "read"],
  ["sfmc_get_journey_versions", "List versions of a journey.", "Journeys", "read"],
  ["sfmc_get_journeys", "List journeys in the current account.", "Journeys", "read"],
  [
    "sfmc_insert_contacts_into_journey_async",
    "Asynchronously insert contacts into a journey.",
    "Journeys",
    "write",
  ],
  [
    "sfmc_insert_contacts_into_journey_status",
    "Check a batch journey insertion status.",
    "Journeys",
    "read",
  ],
  ["sfmc_pause_journey", "Pause a running journey.", "Journeys", "write"],
  ["sfmc_publish_journey", "Asynchronously publish a journey version.", "Journeys", "write"],
  [
    "sfmc_random_split_activity",
    "Construct an in-memory random split activity.",
    "Journeys",
    "read",
  ],
  [
    "sfmc_refresh_transactional_email",
    "Refresh transactional email definition content.",
    "Journeys",
    "write",
  ],
  [
    "sfmc_republish_journey_content",
    "Refresh email content in a running journey.",
    "Journeys",
    "write",
  ],
  ["sfmc_republish_triggered_send", "Refresh classic triggered-send content.", "Journeys", "write"],
  ["sfmc_resume_journey", "Resume a paused journey.", "Journeys", "write"],
  ["sfmc_sms_activity", "Construct an in-memory journey SMS activity.", "Journeys", "read"],
  ["sfmc_stop_journey", "Permanently stop a running journey.", "Journeys", "destructive"],
  ["sfmc_update_event_definition", "Modify a journey event definition.", "Journeys", "destructive"],
  ["sfmc_update_journey", "Modify journey content.", "Journeys", "destructive"],
  ["sfmc_wait_activity", "Construct an in-memory journey wait activity.", "Journeys", "read"],

  ["sfmc_send_push_notification", "Send a push notification immediately.", "Push", "write"],

  [
    "sfmc_create_mobileconnect_keyword",
    "Create a MobileConnect keyword.",
    "SMS messaging",
    "write",
  ],
  [
    "sfmc_create_sms_definition",
    "Create a transactional SMS definition.",
    "SMS messaging",
    "write",
  ],
  ["sfmc_create_sms_send_definition", "Create an SMS send definition.", "SMS messaging", "write"],
  [
    "sfmc_get_mobileconnect_codes",
    "Retrieve MobileConnect short- or long-code configurations.",
    "SMS messaging",
    "read",
  ],
  ["sfmc_get_sms_definition", "Retrieve an SMS definition by key.", "SMS messaging", "read"],
  ["sfmc_get_sms_definitions", "List transactional SMS definitions.", "SMS messaging", "read"],
  [
    "sfmc_get_sms_subscription_status",
    "Retrieve an SMS subscription status.",
    "SMS messaging",
    "read",
  ],
  [
    "sfmc_send_outbound_sms_message",
    "Send a transactional SMS immediately.",
    "SMS messaging",
    "write",
  ],

  [
    "sfmc_get_tracking_events",
    "Retrieve email tracking and engagement events.",
    "Tracking",
    "read",
  ],

  ["sfmc_describe_object", "Describe Marketing Cloud object properties.", "Utilities", "read"],
  ["sfmc_get_lists", "Retrieve subscriber lists.", "Utilities", "read"],
  ["sfmc_get_send_classifications", "Retrieve send classifications.", "Utilities", "read"],
  ["sfmc_get_sender_profiles", "Retrieve sender profiles.", "Utilities", "read"],
  ["sfmc_get_timezones", "List Marketing Cloud time zones.", "Utilities", "read"],
]);
