/* SPDX-License-Identifier: Apache-2.0 */
/** Reviewed Tableau MCP tool contract from Tableau's published tool reference. */
import { defineTools } from "./tool-contract-types.ts";

export const TABLEAU_MCP_TOOLS = defineTools([
  [
    "query-admin-insights",
    "Query Tableau administrative insights for site activity and adoption analysis.",
    "Administration insights",
    "read",
  ],
  [
    "delete-content",
    "Delete supported Tableau content by identifier.",
    "Content administration",
    "destructive",
  ],
  [
    "search-content",
    "Search Tableau content available to the current user.",
    "Content discovery",
    "read",
  ],
  [
    "scaffold-data-app",
    "Generate a starter Tableau data application.",
    "Data application authoring",
    "write",
  ],
  [
    "get-datasource-metadata",
    "Get field and metadata details for a Tableau data source.",
    "Data source inspection",
    "read",
  ],
  [
    "list-datasources",
    "List Tableau data sources available to the current user.",
    "Data source discovery",
    "read",
  ],
  [
    "query-datasource",
    "Run a governed analytical query against a Tableau data source.",
    "Data analysis",
    "read",
  ],
  ["cancel-flow-run", "Cancel an active Tableau Prep flow run.", "Flow execution", "destructive"],
  [
    "describe-flow",
    "Describe a Tableau Prep flow and its inputs, outputs, and steps.",
    "Flow inspection",
    "read",
  ],
  [
    "get-flow-task",
    "Get details for one scheduled Tableau Prep flow task.",
    "Flow inspection",
    "read",
  ],
  ["get-flow", "Get details for one Tableau Prep flow.", "Flow inspection", "read"],
  ["list-flow-runs", "List Tableau Prep flow runs and their status.", "Flow monitoring", "read"],
  ["list-flow-tasks", "List scheduled Tableau Prep flow tasks.", "Flow discovery", "read"],
  [
    "list-flows",
    "List Tableau Prep flows available to the current user.",
    "Flow discovery",
    "read",
  ],
  ["run-flow-task", "Start a configured Tableau Prep flow task.", "Flow execution", "write"],
  ["run-flow", "Start a Tableau Prep flow run.", "Flow execution", "write"],
  ["list-jobs", "List Tableau background jobs and their status.", "Job monitoring", "read"],
  [
    "inspect-knowledge-context",
    "Inspect the configuration of a Tableau knowledge context.",
    "Knowledge context inspection",
    "read",
  ],
  [
    "manage-knowledge-context",
    "Create, update, or otherwise manage Tableau knowledge contexts.",
    "Knowledge context administration",
    "mixed",
  ],
  [
    "query-knowledge-context",
    "Query a configured Tableau knowledge context.",
    "Knowledge context analysis",
    "read",
  ],
  [
    "list-projects",
    "List Tableau projects available to the current user.",
    "Project discovery",
    "read",
  ],
  [
    "generate-pulse-insight-brief",
    "Generate an insight brief for a Tableau Pulse metric.",
    "Pulse insights",
    "read",
  ],
  [
    "generate-pulse-metric-value-insight-bundle",
    "Generate an insight bundle for a Tableau Pulse metric value.",
    "Pulse insights",
    "read",
  ],
  [
    "list-all-pulse-metric-definitions",
    "List all Tableau Pulse metric definitions available to the current user.",
    "Pulse discovery",
    "read",
  ],
  [
    "list-pulse-metric-definitions-from-definition-ids",
    "Get Tableau Pulse metric definitions for specified definition identifiers.",
    "Pulse discovery",
    "read",
  ],
  [
    "list-pulse-metric-subscriptions",
    "List Tableau Pulse metric subscriptions for the current user.",
    "Pulse discovery",
    "read",
  ],
  [
    "list-pulse-metrics-from-metric-definition-id",
    "List Tableau Pulse metrics for one metric definition identifier.",
    "Pulse discovery",
    "read",
  ],
  [
    "list-pulse-metrics-from-metric-ids",
    "Get Tableau Pulse metrics for specified metric identifiers.",
    "Pulse discovery",
    "read",
  ],
  [
    "list-extract-refresh-tasks",
    "List Tableau extract refresh tasks and schedules.",
    "Extract refresh discovery",
    "read",
  ],
  [
    "update-cloud-extract-refresh-task",
    "Update a Tableau Cloud extract refresh task.",
    "Extract refresh administration",
    "write",
  ],
  [
    "reset-consent",
    "Reset stored Tableau MCP consent for the current user.",
    "Token administration",
    "destructive",
  ],
  [
    "revoke-access-token",
    "Revoke the current Tableau MCP access token.",
    "Token administration",
    "destructive",
  ],
  ["list-users", "List users on the current Tableau site.", "User discovery", "read"],
  ["update-user", "Update a user on the current Tableau site.", "User administration", "write"],
  ["get-custom-view-data", "Get underlying data for a Tableau custom view.", "View data", "read"],
  ["get-custom-view-image", "Render an image of a Tableau custom view.", "View rendering", "read"],
  ["get-view-data", "Get underlying data for a Tableau view.", "View data", "read"],
  ["get-view-image", "Render an image of a Tableau view.", "View rendering", "read"],
  [
    "list-custom-views",
    "List Tableau custom views available to the current user.",
    "View discovery",
    "read",
  ],
  ["list-views", "List Tableau views available to the current user.", "View discovery", "read"],
  ["download-workbook", "Download a Tableau workbook.", "Workbook retrieval", "read"],
  ["get-workbook", "Get details for one Tableau workbook.", "Workbook inspection", "read"],
  [
    "list-workbooks",
    "List Tableau workbooks available to the current user.",
    "Workbook discovery",
    "read",
  ],
  ["publish-workbook", "Publish a workbook to Tableau.", "Workbook publishing", "write"],
  [
    "request-workbook-upload",
    "Request an upload session for publishing a Tableau workbook.",
    "Workbook publishing",
    "write",
  ],
]);
